server:
  port: 3100
spring:
  application:
    name: abc-usercenter
  datasource:
    url: jdbc:mysql://localhost:3306/securitylogin?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root159
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss