server:
  port: 2200
spring:
  application:
    name: abc-usercenter
  datasource:
    url: jdbc:mysql://localhost:3306/securitylogin?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root159
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
    lettuce:
      pool:
        # 连接池最大连接数（负值无限制）
        max-active: 200
        # 最大空闲连接
        max-idle: 20
        # 最小空闲连接
        min-idle: 0
        # 最大阻塞等待时间（负值无限制）
        max-wait: -1ms
    timeout: 100ms
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

security:
  oauth:
    token:
      store: redis