server:
  port: 2200
spring:
  application:
    name: abc-auth
eureka:
  client:
    registerWithEureka: true #服务注册，是否将自己注册到Eureka服务中
    fetchRegistry: true #服务发现，是否从Eureka中获取注册信息
    service-url:
      defaultZone: http://e1.abc.com:2001/eureka/
feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 100