server:
  port: 2400
spring:
  application:
    name: abc-auth
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
eureka:
  client:
    registerWithEureka: true #服务注册，是否将自己注册到Eureka服务中
    fetchRegistry: true #服务发现，是否从Eureka中获取注册信息
    service-url:
      defaultZone: http://e1.abc.com:2001/eureka/
feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 100
